/**
 * GENERATED by scripts/bake-audio.mjs -- do not edit by hand.
 *
 * AUDIO is a literal object on purpose: `keyof typeof AUDIO` then gives the
 * exact slot-name union, so a misspelled name in a call site is a compile
 * error rather than a hit that silently never plays. Do NOT add an index
 * signature to it -- that would erase the union and the guarantee with it.
 */

export type AudioBus = "music" | "ambience" | "foley" | "hardfx" | "ui" | "sub";

export interface AudioVariant {
  /** public path, already cache-busted by the build */
  readonly path: string;
  readonly bytes: number;
  /** decoded duration in seconds */
  readonly dur: number;
}

export interface AudioSlot {
  readonly cat: string;
  readonly bus: AudioBus;
  readonly ch: 1 | 2;
  /** suggested playback gain in dB; loudness is already matched per category */
  readonly gain: number;
  /** suggested room send in dB relative to gain */
  readonly send: number;
  readonly v: readonly AudioVariant[];
}

export const AUDIO = {
  "amb.rain": {
    cat: "amb", bus: "ambience", ch: 2,
    gain: 0, send: -14,
    v: [
      { path: "/audio/amb/rain_00.m4a", bytes: 260943, dur: 10 },
    ],
  },
  "amb.room-crt": {
    cat: "amb", bus: "ambience", ch: 2,
    gain: 0, send: -16,
    v: [
      { path: "/audio/amb/room-crt_00.m4a", bytes: 293548, dur: 12 },
    ],
  },
  "amb.room-desk": {
    cat: "amb", bus: "ambience", ch: 2,
    gain: 0, send: -15,
    v: [
      { path: "/audio/amb/room-desk_00.m4a", bytes: 294040, dur: 12 },
    ],
  },
  "cin.paper-tear": {
    cat: "cin", bus: "hardfx", ch: 1,
    gain: -1, send: -6,
    v: [
      { path: "/audio/cin/paper-tear_00.m4a", bytes: 14823, dur: 0.8 },
      { path: "/audio/cin/paper-tear_01.m4a", bytes: 14974, dur: 0.8 },
      { path: "/audio/cin/paper-tear_02.m4a", bytes: 14940, dur: 0.8 },
      { path: "/audio/cin/paper-tear_03.m4a", bytes: 15041, dur: 0.8 },
    ],
  },
  "fol.paper-flip": {
    cat: "fol", bus: "foley", ch: 1,
    gain: -4, send: -8,
    v: [
      { path: "/audio/fol/paper-flip_00.m4a", bytes: 6618, dur: 0.45 },
      { path: "/audio/fol/paper-flip_01.m4a", bytes: 6434, dur: 0.45 },
      { path: "/audio/fol/paper-flip_02.m4a", bytes: 6098, dur: 0.45 },
      { path: "/audio/fol/paper-flip_03.m4a", bytes: 6145, dur: 0.45 },
      { path: "/audio/fol/paper-flip_04.m4a", bytes: 6087, dur: 0.45 },
    ],
  },
  "imp.press-clank": {
    cat: "imp", bus: "hardfx", ch: 1,
    gain: 0, send: -7,
    v: [
      { path: "/audio/imp/press-clank_00.m4a", bytes: 14520, dur: 0.9 },
      { path: "/audio/imp/press-clank_01.m4a", bytes: 13640, dur: 0.9 },
      { path: "/audio/imp/press-clank_02.m4a", bytes: 13812, dur: 0.9 },
      { path: "/audio/imp/press-clank_03.m4a", bytes: 13443, dur: 0.9 },
    ],
  },
  "imp.press-slam": {
    cat: "imp", bus: "hardfx", ch: 1,
    gain: 0, send: -5,
    v: [
      { path: "/audio/imp/press-slam_00.m4a", bytes: 23417, dur: 2.6 },
      { path: "/audio/imp/press-slam_01.m4a", bytes: 25196, dur: 2.6 },
    ],
  },
  "imp.title-drop": {
    cat: "imp", bus: "hardfx", ch: 1,
    gain: 0, send: -6,
    v: [
      { path: "/audio/imp/title-drop_00.m4a", bytes: 20434, dur: 1.8 },
      { path: "/audio/imp/title-drop_01.m4a", bytes: 20431, dur: 1.8 },
    ],
  },
  "ui.key": {
    cat: "ui", bus: "ui", ch: 1,
    gain: -7, send: -12,
    v: [
      { path: "/audio/ui/key_00.m4a", bytes: 2664, dur: 0.18 },
      { path: "/audio/ui/key_01.m4a", bytes: 2923, dur: 0.18 },
      { path: "/audio/ui/key_02.m4a", bytes: 2785, dur: 0.18 },
      { path: "/audio/ui/key_03.m4a", bytes: 2751, dur: 0.18 },
      { path: "/audio/ui/key_04.m4a", bytes: 2851, dur: 0.18 },
      { path: "/audio/ui/key_05.m4a", bytes: 2563, dur: 0.18 },
      { path: "/audio/ui/key_06.m4a", bytes: 2775, dur: 0.18 },
      { path: "/audio/ui/key_07.m4a", bytes: 2578, dur: 0.18 },
      { path: "/audio/ui/key_08.m4a", bytes: 2775, dur: 0.18 },
      { path: "/audio/ui/key_09.m4a", bytes: 2856, dur: 0.18 },
    ],
  },
  "ui.key-space": {
    cat: "ui", bus: "ui", ch: 1,
    gain: -7, send: -12,
    v: [
      { path: "/audio/ui/key-space_00.m4a", bytes: 2390, dur: 0.2 },
      { path: "/audio/ui/key-space_01.m4a", bytes: 2487, dur: 0.2 },
      { path: "/audio/ui/key-space_02.m4a", bytes: 2481, dur: 0.2 },
    ],
  },
} as const;

export type AudioName = keyof typeof AUDIO;

/** 33 files, 1119463 bytes total on disk */
export const AUDIO_BYTES = 1119463;
