/**
 * GENERATED by scripts/bake-audio.mjs -- do not edit by hand.
 *
 * AUDIO is a literal object on purpose: `keyof typeof AUDIO` then gives the
 * exact slot-name union, so a misspelled name in a call site is a compile
 * error rather than a hit that silently never plays. Do NOT add an index
 * signature to it -- that would erase the union and the guarantee with it.
 */

export type AudioBus = "music" | "ambience" | "foley" | "hardfx" | "ui" | "sub";

export interface AudioVariant {
  readonly path: string;
  readonly bytes: number;
  /** decoded duration in seconds */
  readonly dur: number;
  /** first 16 hex of the encoded file's sha256; --check verifies it */
  readonly sha: string;
}

export interface AudioSlot {
  readonly cat: string;
  readonly bus: AudioBus;
  readonly ch: 1 | 2;
  /** suggested playback gain in dB; loudness is already matched per category */
  readonly gain: number;
  /** suggested room send in dB relative to gain */
  readonly send: number;
  /** true for beds the runtime loops through its crossfading bed player */
  readonly loop: boolean;
  readonly v: readonly AudioVariant[];
}

export const AUDIO = {
  "amb.rain": {
    cat: "amb", bus: "ambience", ch: 2,
    gain: 0, send: -14, loop: true,
    v: [
      { path: "/audio/amb/rain_00.m4a", bytes: 292944, dur: 11.981, sha: "6dbb04f210548d5d" },
    ],
  },
  "amb.room-crt": {
    cat: "amb", bus: "ambience", ch: 2,
    gain: 0, send: -16, loop: true,
    v: [
      { path: "/audio/amb/room-crt_00.m4a", bytes: 293488, dur: 12, sha: "adce8ea6fee366e9" },
    ],
  },
  "amb.room-desk": {
    cat: "amb", bus: "ambience", ch: 2,
    gain: 0, send: -15, loop: true,
    v: [
      { path: "/audio/amb/room-desk_00.m4a", bytes: 291760, dur: 11.981, sha: "ecb241609ad751b8" },
    ],
  },
  "cin.paper-tear": {
    cat: "cin", bus: "hardfx", ch: 1,
    gain: -1, send: -6, loop: false,
    v: [
      { path: "/audio/cin/paper-tear_00.m4a", bytes: 17484, dur: 1.043, sha: "4c8dd0800c3b5fb8" },
      { path: "/audio/cin/paper-tear_01.m4a", bytes: 25025, dur: 1.384, sha: "deba531d0553675d" },
      { path: "/audio/cin/paper-tear_02.m4a", bytes: 18876, dur: 1.102, sha: "e980fcce819d1932" },
      { path: "/audio/cin/paper-tear_03.m4a", bytes: 21876, dur: 1.303, sha: "d2baccead07e0796" },
    ],
  },
  "cin.spread-unfold": {
    cat: "cin", bus: "hardfx", ch: 1,
    gain: -1, send: -5, loop: false,
    v: [
      { path: "/audio/cin/spread-unfold_00.m4a", bytes: 22947, dur: 1.256, sha: "0f412bfef84a7a32" },
    ],
  },
  "fol.meow": {
    cat: "fol", bus: "foley", ch: 1,
    gain: -4, send: -9, loop: false,
    v: [
      { path: "/audio/fol/meow_00.m4a", bytes: 21613, dur: 1.32, sha: "0b1e20f1d9457a0d" },
      { path: "/audio/fol/meow_01.m4a", bytes: 20272, dur: 1.213, sha: "d7aa2753a7caa419" },
      { path: "/audio/fol/meow_02.m4a", bytes: 16809, dur: 1.007, sha: "58b99034d1fb8977" },
      { path: "/audio/fol/meow_03.m4a", bytes: 20312, dur: 1.235, sha: "788c8684380105e2" },
    ],
  },
  "fol.paper-flip": {
    cat: "fol", bus: "foley", ch: 1,
    gain: -4, send: -8, loop: false,
    v: [
      { path: "/audio/fol/paper-flip_00.m4a", bytes: 21959, dur: 1.199, sha: "894d5532937f0f98" },
      { path: "/audio/fol/paper-flip_01.m4a", bytes: 20864, dur: 1.12, sha: "270e81bda3b2e8fa" },
      { path: "/audio/fol/paper-flip_02.m4a", bytes: 17157, dur: 0.951, sha: "76d3ecb78f0c1ca0" },
      { path: "/audio/fol/paper-flip_03.m4a", bytes: 20600, dur: 1.2, sha: "a0abf04ca0e64bb4" },
      { path: "/audio/fol/paper-flip_04.m4a", bytes: 18100, dur: 1.049, sha: "a3b24fa66d7909b3" },
    ],
  },
  "imp.press-clank": {
    cat: "imp", bus: "hardfx", ch: 1,
    gain: 0, send: -7, loop: false,
    v: [
      { path: "/audio/imp/press-clank_00.m4a", bytes: 13882, dur: 0.82, sha: "d3a2ee525d6c284a" },
      { path: "/audio/imp/press-clank_01.m4a", bytes: 12417, dur: 0.728, sha: "8c6e15e7bce015d4" },
      { path: "/audio/imp/press-clank_02.m4a", bytes: 11643, dur: 0.675, sha: "82406e0ee710fa34" },
      { path: "/audio/imp/press-clank_03.m4a", bytes: 14578, dur: 0.853, sha: "ff5ffb8d2c26422b" },
    ],
  },
  "imp.press-slam": {
    cat: "imp", bus: "hardfx", ch: 1,
    gain: 0, send: -5, loop: false,
    v: [
      { path: "/audio/imp/press-slam_00.m4a", bytes: 31344, dur: 1.946, sha: "70fdd4d9771a7d3d" },
      { path: "/audio/imp/press-slam_01.m4a", bytes: 26164, dur: 1.536, sha: "5d335b25879c6c61" },
    ],
  },
  "imp.title-drop": {
    cat: "imp", bus: "hardfx", ch: 1,
    gain: 0, send: -6, loop: false,
    v: [
      { path: "/audio/imp/title-drop_00.m4a", bytes: 29579, dur: 1.8, sha: "ff9847d2ffacbc56" },
      { path: "/audio/imp/title-drop_01.m4a", bytes: 27470, dur: 1.704, sha: "c16c883c3d4d1b72" },
    ],
  },
  "mus.score": {
    cat: "mus", bus: "music", ch: 2,
    gain: 0, send: -14, loop: true,
    v: [
      { path: "/audio/mus/score_00.m4a", bytes: 2997702, dur: 120.001, sha: "c740c13fa7bebf67" },
    ],
  },
  "ui.key": {
    cat: "ui", bus: "ui", ch: 1,
    gain: -7, send: -12, loop: false,
    v: [
      { path: "/audio/ui/key_00.m4a", bytes: 5469, dur: 0.263, sha: "a278c7a1475d7020" },
      { path: "/audio/ui/key_01.m4a", bytes: 5658, dur: 0.288, sha: "b292d4b754f4caf7" },
      { path: "/audio/ui/key_02.m4a", bytes: 7344, dur: 0.36, sha: "a5b15e401f43e8c2" },
      { path: "/audio/ui/key_03.m4a", bytes: 6212, dur: 0.29, sha: "b17d47e44c2ec077" },
      { path: "/audio/ui/key_04.m4a", bytes: 6678, dur: 0.331, sha: "7454fa4788a5ff2c" },
      { path: "/audio/ui/key_05.m4a", bytes: 5390, dur: 0.233, sha: "d7c3827550795274" },
      { path: "/audio/ui/key_06.m4a", bytes: 5794, dur: 0.266, sha: "239d0dcba5b7d856" },
      { path: "/audio/ui/key_07.m4a", bytes: 6253, dur: 0.31, sha: "69509ad740155b73" },
      { path: "/audio/ui/key_08.m4a", bytes: 7127, dur: 0.365, sha: "198cc987a3fc8b18" },
      { path: "/audio/ui/key_09.m4a", bytes: 5266, dur: 0.241, sha: "783ac19c17619db7" },
    ],
  },
} as const satisfies Record<string, AudioSlot>;

export type AudioName = keyof typeof AUDIO;

/** 36 files, 4388056 bytes total on disk */
export const AUDIO_BYTES = 4388056;
